export { App } from './App/App';
export { Header } from './Header/Header';
export { MainPage } from './MainPage/MainPage';
export { Offers } from './Offers/Offers';
export { Promotions } from './Promotions/Promotions';
export { Assortment } from './Assortment/Assortment';
export { AssortmentItem } from './AssortmentItem/AssortmentItem';
export { Advantages} from './Advantages/Advantages';
export { News } from './News/News';
export { SubscriptionForm } from './SubscriptionForm/SubscriptionForm';
export { Contacts } from './Contacts/Contacts';
